version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      major-updates:
        patterns:
          - "*"
        update-types: ["major"]
    labels:
      - "dependencies"
      - "major-update"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    versioning-strategy: "increase"
